### ISSUE TITLE
注释中的 {@code false} 没有显示出来

### ISSUE THREAD

**Issue by Aurorxa** [LinWanCen/show-comment#14]
![image](https://user-images.githubusercontent.com/25677587/199140980-6ac68c99-20ff-4ce0-99fc-e53eaed5858d.png)
![image](https://user-images.githubusercontent.com/25677587/199141016-2086f255-204f-4749-ad44-d4ca66d0b27b.png)

**Comment by LinWanCen** [comment]
非常感谢您的反馈，最近被安排去支持生产经常忙到很晚下班。

看了下是因为@link的时候空格算一个独立子对象，@code时和后面的字符串合并，觉得是JB平台的设计问题。

改成从后往前取来兼容了。
更新到2.05.0.2022.11.04_22.59即可。

**Comment by Aurorxa** [comment]
好的，非常感谢~
