### ISSUE TITLE
您好,支持go语言的goland编辑器吗?

### ISSUE THREAD

**Issue by feng99** [LinWanCen/show-comment#15]
您好,支持go语言的goland编辑器吗?
或者在idea中  支持识别go语言的代码注释  谢谢

**Comment by LinWanCen** [comment]
2.0支持

**Comment by LinWanCen** [comment]
最低支持2020.1版本，你的版本是？

**Comment by LinWanCen** [comment]
2021.3会报错，是IDEA禁止解析语法这种消耗性能的操作，但我已经用了异步，只会占用资源不会占用UI时间。

**Comment by feng99** [comment]
2021.2.4 
找到了   感谢

**Comment by feng99** [comment]
已Star
