### ISSUE TITLE
java.lang.Exception

### ISSUE THREAD

**Issue by SophieRoyal** [LinWanCen/show-comment#16]
![image](https://user-images.githubusercontent.com/37917658/203200481-f316f388-235c-4207-9bd8-c9d7f34bb2d2.png)

**Comment by LinWanCen** [comment]
您好，可否粘贴完整堆栈，截图里看不到哪里报错

**Comment by SophieRoyal** [comment]
本来要贴的，结果后来有事忘记了。我明天看看，是上一个版本的。报错后我升最新版了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月22日 10:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [LinWanCen/show-comment] java.lang.Exception (Issue #16) |

您好，可否粘贴完整堆栈，截图里看不到哪里报错
