### ISSUE TITLE
建议：备注的内容可以通过键盘输入过滤跳转

### ISSUE THREAD

**Issue by dongchengjie** [LinWanCen/show-comment#17]
IDEA光标聚焦到树上，然后输入文本可以过滤，文字变黄同时滚动到相应位置
而插件只能够使备注的文本变色，而不能让滚动条滚动到相应文件或目录

**Comment by LinWanCen** [comment]
文件树是拓展信息，用的是IDEA自带的功能，就是显示覆盖率或文件修改时间那个，IDEA官方应该不会对搜索做这个修改。
你的具体需求场景是什么，是不是可以用全文正则表达式搜索来达到目的。

突然想起

很多时候对方提了个建议短时间很难完成，或者反复修改，实际上是因为没解决对方的需求，而建议是想到的解决其需求的不那么好的方案，收到建议时多问一下对方建议背后的需求，然后再根据需求设计不同时间和资源下的解决方案给对方选择。——by 广发银行研发中心总经理 李怀根

终于融会贯通了

**Comment by LinWanCen** [comment]
文件树是拓展信息，用的是IDEA自带的功能，就是显示覆盖率或文件修改时间那个，IDEA官方应该不会对搜索做这个修改。
你的具体需求场景是什么，是不是可以用全文正则表达式搜索来达到目的。

突然想起

很多时候对方提了个建议短时间很难完成，或者反复修改，实际上是因为没解决对方的需求，而建议是想到的解决其需求的不那么好的方案，收到建议时多问一下对方建议背后的需求，然后再根据需求设计不同时间和资源下的解决方案给对方选择。——by 广发银行研发中心总经理 李怀根

终于融会贯通了

**Comment by LinWanCen** [comment]
文件树是拓展信息，用的是IDEA自带的功能，就是显示覆盖率或文件修改时间那个，IDEA官方应该不会对搜索做这个修改。
你的具体需求场景是什么，是不是可以用全文正则表达式搜索来达到目的。

突然想起

要分清楚需求和方案，很多时候对方提了个需求短时间很难完成，或者反复修改，实际上是因为提出来的是方案或建议，而这个方案没解决对方的需求，而建议是想到的解决其需求的过于完善或不完善的方案，收到建议时多问一下对方建议背后的需求，然后再根据需求设计不同时间和资源下的解决方案给对方选择。——by 广发银行研发中心总经理 李怀根

终于融会贯通了

**Comment by LinWanCen** [comment]
文件树是拓展信息，用的是IDEA自带的功能，就是显示覆盖率或文件修改时间那个，IDEA官方应该不会对搜索做这个修改。
你的具体需求场景是什么，是不是可以用全文正则表达式搜索解决。
