### ISSUE TITLE
Annontation 注解类不显示说明

### ISSUE THREAD

**Issue by Suomm** [LinWanCen/show-comment#18]
如题，见下：
---
![image](https://user-images.githubusercontent.com/27558987/206650627-f24755e0-3968-4ec3-8db5-3d5caf5b52ab.png)
---
![image](https://user-images.githubusercontent.com/27558987/206650708-77751643-0db3-495a-8f08-91fe907c61da.png)

**Comment by LinWanCen** [comment]
大概知道怎么回事，以前是写来跳过行注释的注解的，后面算法统一之后就导致树注释也没了，待我调整下。

**Comment by LinWanCen** [comment]
插件市场已经通过了昨晚的新版本2.06
