### ISSUE TITLE
关于插件配置的建议

### ISSUE THREAD

**Issue by Suomm** [LinWanCen/show-comment#19]
- 添加 “重置为默认配置” 按钮，一键恢复默认配置（非常希望）
- 添加配置文件 “导入” / “导出” 功能（有待讨论）

**Comment by LinWanCen** [comment]
设置的重置和序列化是IDEA框架自带的，暂未找到好的方式去实现这个功能。
你可以通过删除配置文件来恢复默认配置，或者备份设置文件：

C:\Users\用户名\AppData\Roaming\JetBrains\IntelliJIdea2022.1\options\ShowCommentGlobal.xml

项目\.idea\ShowCommentProject.xml

**Comment by LinWanCen** [comment]
插件市场已通过
