### ISSUE TITLE
是否能适配goland,并且建议增加目录和文件注释显示

### ISSUE THREAD

**Issue by xushushun** [LinWanCen/show-comment#2]
是否能适配goland,并且建议增加目录和文件注释显示

**Comment by LinWanCen** [comment]
目录和文件注释可以用外部注释功能，在xxx.tree.tsv文件中第一列放文件名(可省略拓展名)，第二列放注释。
尝试在goland上安装后报找不到类异常，导致IDEA界面都异常了，官网对兼容性开发描述不太具体，我研究下。

**Comment by LinWanCen** [comment]
最近重构了了下，目前遇到无法把go设置成插件的问题，类似这个，请教了微信插件的大佬看看能不能解决：https://intellij-support.jetbrains.com/hc/en-us/community/posts/4405908484114-Cannot-find-builtin-plugin，目前对go语言本身的解析还没做，如果不能实现一个插件支持多语言的话得考虑要不要做不同版本支持不同IDE。先给你个在Goland中可安装的版本：
[show-comment-1.20.0.2022.06.26_22.25.zip](https://github.com/LinWanCen/show-comment/files/8987055/show-comment-1.20.0.2022.06.26_22.25.zip)

**Comment by xushushun** [comment]
> 最近重构了了下，遇到无法把 go 设置成插件的问题，类似这个，请教了微信插件的大佬看看能不能解决： https://intellij-support.jetbrains.com/hc/en-us/community/posts/4405908484114-Cannot-find-builtin-plugin
> 
> 目前对go语言本身的解析还没做， 如果不能实现一个插件支持多语言的话得考虑要不要做不同版本支持不同IDE。
> 
> 先给你个在Goland中可安装的版本：
> 
> [show-comment-1.20.0.2022.06.26_22.25.zip](https://github.com/LinWanCen/show-comment/files/8987055/show-comment-1.20.0.2022.06.26_22.25.zip)
> 
> 注意 xxx.tree.tsv 配置文件的两列要用 tab 来分隔， 可以从 go 源码中复制过来，或者用 Excel 整理好文件名对应的注释再粘贴进去。

请问这个xxx.tree.tsv 中的xxx是什么 我在一个目录下新建一个tsv 然后里面输入 文件名 tab符 后注释名 goland没作用 右下角有ext doc file load complete提示

**Comment by LinWanCen** [comment]
xxx可以是任意内容，后缀是.tree.tsv就可以，idea树注释不会实时刷新，只有增删移文件或者重新打开项目才会更新。

**Comment by LinWanCen** [comment]
突然想起来，格式是xxx.拓展名.tree.tsv🤣
最近重构兼容全部 IDE 改了好多代码，迟迟未上线。

**Comment by xushushun** [comment]
> 突然想起来，格式是xxx.拓展名.tree.tsv🤣 最近重构兼容全部 IDE 改了好多代码，迟迟未上线。

我说呢哈哈怎么搞都不起作用

**Comment by LinWanCen** [comment]
虽然你可能不是要行注释，不过这个漫长的重构和内测还有兼容性的2.0改造终于完工了。
支持所有 JetBrains 软件和 SQL, JavaScript, Python, Golang, Kotlin.
插件市场已经审批通过，可以更新了ヾ(≧▽≦*)o
