### ISSUE TITLE
怎么在树结构显示指定字段

### ISSUE THREAD

**Issue by Pluto4o4** [LinWanCen/show-comment#20]
这是我的注释格式
```
/**
 * @Author Mr.Xu/Pluto404
 * @Description 注释
 * @Date 12:19 2022/12/13
 * @Param 
 * @return 
 **/
```
怎么设置在树结构显示description后面的注释。

**Comment by LinWanCen** [comment]
这里可以设置你要的标签，不过建议你用正确的注释写法，类似第一行写简洁说明，第二行写对照说明，第三行写详细说明，换行用<br>，这样在 Ctrl + Q 查看和生成 javadoc 的时候才能生成规范的文档且不会报错，在 IDEA 中不会报黄。
PS: author 和 date 的首字母不应大写
![设置说明](https://user-images.githubusercontent.com/14926671/207310865-e38e0f33-3b56-4fc7-ac31-76668e860ed6.png)

**Comment by Pluto4o4** [comment]
> 这里可以设置你要的标签，不过建议你用正确的注释写法，类似第一行写简洁说明，第二行写对照说明，第三行写详细说明，换行用，这样在 Ctrl + Q 查看和生成 javadoc 的时候才能生成规范的文档且不会报错，在 IDEA 中不会报黄。 PS： author 和 date 的首字母不应大写`<br>` ![设置说明](https://user-images.githubusercontent.com/14926671/207310865-e38e0f33-3b56-4fc7-ac31-76668e860ed6.png)

谢谢解答，我知道了注释的格式问题，已经改正。

**Comment by gongxianshengjiadexiaohuihui** [comment]
![image](https://github.com/LinWanCen/show-comment/assets/39046975/a2a8f90d-4012-4378-b93e-0d309a2e2e91)
我参考#20设置了，依然不生效，是怎么回事
