### ISSUE TITLE
建议: 移动设置菜单到 [其他设置]

### ISSUE THREAD

**Issue by syrm-ll** [LinWanCen/show-comment#22]
![image](https://user-images.githubusercontent.com/40515646/207795368-5627fcda-9f58-4057-918e-67420ce58104.png)

1. `设置 > 工具` 分组很多都是 IDE 内置工具,  很多插件设置都放在 `设置 > 其他设置分组`

2. 设置项菜单名称的 `//` 很违和啊 🤣

2. 另外, 项目设置很多时候并非必须, 不应该占据一级菜单入口  能否像 `MyBatisCodeHelperPro` 一样放在默认折叠的二级菜单里
![image](https://user-images.githubusercontent.com/40515646/207795843-de8e54aa-247b-4c0e-8357-5b4d881f8666.png)

**Comment by LinWanCen** [comment]
1. 放工具是IDEA官方要求改的，你应该跟其他插件提建议让他们改到tool。
参考：https://plugins.jetbrains.com/docs/intellij/settings-guide.html#extension-points-for-settings

Do not use this group. Use the tools group instead.

2. 前面的 // 不会去掉这个是插件的特点

3. 项目设置放在全局设置下这个采纳。

PS：设置菜单有空我会改成支持中文。

**Comment by syrm-ll** [comment]
我以为插件都放 其他设置呢 🤣
以前只有翻译一个插件设置在工具里
