### ISSUE TITLE
疑问: 项目根目录 pid 文件出现意料之外的注释

### ISSUE THREAD

**Issue by syrm-ll** [LinWanCen/show-comment#23]
![image](https://user-images.githubusercontent.com/40515646/207798479-cab36d0a-6b50-41af-80de-bb38128ac2ff.png)

如图, 只有一个项目里会这样, 其他项目不会
注释内容在项目里没有搜索到, 应该是三方库里的注释, 但是不知道是哪个文件

**Comment by LinWanCen** [comment]
可能来自 Pid.java
这个功能是为了
显示 Mapper.xml 对应的接口注释
显示 类名后缀.json 文件注释

**Comment by syrm-ll** [comment]
![image](https://user-images.githubusercontent.com/40515646/207820887-c34399ee-a6c2-430a-8d3d-f0b82d30da1e.png)

 😄 是的 `cn.hutool.core.lang.Pid` 

如果是为了 mapper.xml 和 .json 应该根据扩展名过滤下
没有扩展名或只有扩展名 (.xxx 这类隐藏文件)  应该忽略

**Comment by LinWanCen** [comment]
插件市场已通过，更新到 2.08.0.2023.01.17_21.22 即可，只有全名符合且有扩展名时才会对小写开头起作用
