### ISSUE TITLE
疑问：有一些我没有写过的注释出现在了文件后面

### ISSUE THREAD

**Issue by Suomm** [LinWanCen/show-comment#25]
![image](https://user-images.githubusercontent.com/27558987/212521321-277fd53b-1a1b-47e3-b92b-11d087bfe880.png)

**Comment by LinWanCen** [comment]
2.06 加的小写自动找大写类注释的功能的副作用，我想想看，是不是这个功能只在全名或者文件名符合某些条件才显示。
2.06 这个功能是为了显示 userMapper.xml 这种文件的注释。

**Comment by LinWanCen** [comment]
插件市场已通过，更新到 2.08.0.2023.01.17_21.22 即可，只有全名符合时才会对小写开头起作用
