### ISSUE TITLE
sql行尾注释中部分字段注释无法显示

### ISSUE THREAD

**Issue by diedie123** [LinWanCen/show-comment#28]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/38551891/226785258-d1418ba5-1e7e-46f4-a2fc-1e488d713438.png">

**Comment by LinWanCen** [comment]
这个是 MySQL 吗？
这里是用 IDEA 原生的注释显示的，读的不是 ddl 的代码注释，是数据库表里的 comment，你可以在字段上 Ctrl + Q 看看 IDEA 自带功能读到的注释，如果显示了注释但是行后面没显示就说明有问题。

**Comment by diedie123** [comment]
oracle数据库
<img width="649" alt="image" src="https://user-images.githubusercontent.com/38551891/226870825-d28d4c0a-8c9d-4298-b059-d19266852bc8.png">

**Comment by diedie123** [comment]
pg库也能复现
<img width="768" alt="image" src="https://user-images.githubusercontent.com/38551891/226871241-885cc312-a9eb-4013-b07c-6bd75f61a3a4.png">

**Comment by LinWanCen** [comment]
判断符号的算法写错了，应该是包含非符号的就不是符号，而不是包含一个符号就算符号，所以下划线被跳过了，已经提交了修复，待插件市场审核。
