### ISSUE TITLE
如何设置才能让插件显示行尾注释

### ISSUE THREAD

**Issue by auto-bot-ty** [LinWanCen/show-comment#38]
如何设置才能让插件显示红框的注释而不是蓝框的注释
<img width="569" alt="image_20" src="https://github.com/LinWanCen/show-comment/assets/75887908/37744db1-7f97-49c2-880b-b83c4db1c5dc">

**Comment by LinWanCen** [comment]
只有文档注释才会被 IDEA 识别，Ctrl + Q 才能显示，行末注释只是省去了 Ctrl + Q 更直观地显示，你可以用如下正则表达式替换，把行末注释变成文档注释：
```
(\s*)(.*)// *(.*)
$1/\*\* $3 \*/\n$1$2
```

**Comment by auto-bot-ty** [comment]
原来是IDEA的限制, 感谢大佬开发的插件
