### ISSUE TITLE
新UI中无法显示

### ISSUE THREAD

**Issue by by123456by** [LinWanCen/show-comment#39]
![image](https://github.com/LinWanCen/show-comment/assets/15666692/05647edc-3d15-4f4d-aa59-60503668fe24)

**Comment by LinWanCen** [comment]
右下角看看是否在建立索引，你的IDEA和插件分别是什么版本，我试试看。

**Comment by by123456by** [comment]
> 右下角看看是否在建立索引，你的IDEA和插件分别是什么版本，我试试看。

当时没有建立索引，并且代码中的行尾注释是有的，刚刚打开idea看到显示了，可能是我第一次切换新UI的某种bug
