### ISSUE TITLE
对于python能否支持下默认的多行注释

### ISSUE THREAD

**Issue by hui-huo** [LinWanCen/show-comment#41]
<img width="505" alt="image" src="https://github.com/LinWanCen/show-comment/assets/55521126/d7cce8a6-32be-4058-a437-4e5d2ccc940e">

默认都是写在函数或者类内部的，为了使用插件单独在外面再去写一个单行注释挺冗余的。多行注释虽然内容多，可以默认支持下只读取多行注释的第一行吗

**Comment by LinWanCen** [comment]
这个是你们项目独有的习惯还是开源项目共有的习惯，如果IDEA本身无法识别（Ctrl+Q显示注释），就涉及到新写解析逻辑，如果不是通用的我不会添加到插件中。
你可以在 PythonLangDoc.java 重写 resolveDocRaw() 实现，或者跟你们项目领导申请由我付费定制开发一个版本给你们公司。

**Comment by hui-huo** [comment]
@LinWanCen 这个是python官方的文档注释规范

**Comment by hui-huo** [comment]
在python中，#只是单行注释，示例是文档注释。

**Comment by LinWanCen** [comment]
我回来试了下，IDEA本身可以识别👍
我研究下，之前还以为 Python 没有文档注释哈哈哈

**Comment by LinWanCen** [comment]
插件市场已经审核通过，更新到 2.09 版本即可。

开发笔记：
Python 文档注释官方文档：https://docs.python.org/zh-cn/3/tutorial/controlflow.html#documentation-strings

注释类关系
![image](https://github.com/LinWanCen/show-comment/assets/14926671/2ad4d5f6-8b32-40c5-a5a4-e9b84a003010)

**Comment by hui-huo** [comment]
@LinWanCen 感谢大佬的支持
