### ISSUE TITLE
方法头多个参数显示效果

### ISSUE THREAD

**Issue by ouyang7923** [LinWanCen/show-comment#42]
![image](https://github.com/LinWanCen/show-comment/assets/105358618/80d65824-df2b-4667-8c41-cdf1cca147c6)
当前有2个参数类，它们的注释显示在一起可能有点混淆，建议显示成格式：
![image](https://github.com/LinWanCen/show-comment/assets/105358618/9775b1c9-e191-4a08-936b-9b990df531a2)
或其他方式加以区分

**Comment by ouyang7923** [comment]
> 

可以的

**Comment by LinWanCen** [comment]
插件市场已经审核通过，更新到 2.09 版本即可。
