### ISSUE TITLE
模块化项目不显示类注释

### ISSUE THREAD

**Issue by Suomm** [LinWanCen/show-comment#43]
当我使用 Java 模块化项目时，创建包含 `module-info.java` 文件的 maven 模块时，只会显示包注释，不会显示类注释和模块注释。

![image](https://github.com/LinWanCen/show-comment/assets/27558987/3929d38a-6939-4668-99f6-b8c00ba2bce4)

**Comment by LinWanCen** [comment]
默认设置忽略了`^(java|cn)\.`开头的包导致，你可以先改回只忽略`^(java)\.`的 JDK 包，新版已提交插件市场待审核。
