### ISSUE TITLE
类文件支持注解后内容展示

### ISSUE THREAD

**Issue by gongxianshengjiadexiaohuihui** [LinWanCen/show-comment#46]
![image](https://github.com/LinWanCen/show-comment/assets/39046975/53960579-51c8-41ab-b231-f19ceb3539d0)
我想展示@Description后的内容

**Comment by gongxianshengjiadexiaohuihui** [comment]
![image](https://github.com/LinWanCen/show-comment/assets/39046975/fe78859d-d47b-4cc1-a3bf-7e4e51e2d4fa)
我参考#20设置了，依然不生效。

**Comment by LinWanCen** [comment]
忽略空白的勾去掉，因为注释原文是空白所以被跳过了
