### ISSUE TITLE
注释排除正则

### ISSUE THREAD

**Issue by linwqwhu** [LinWanCen/show-comment#47]
在pycharm中，格式如下的函数：
```python
    def select_training_samples(self，proposals, argets):
        # type: (...) -> Tuple[List[Tensor], List[Tensor], List[Tensor]]
        """
        划分正负样本，统计对应gt的标签以及边界框回归信息
        """
        pass
```
开启显示”# python“之后，调用函数时后面显示的注释为：”# type: ....."，但我不想显示这句，想显示的是“划分正负样本......”，我分别在“注释排除正则”处添加了正则`/^\#.type:.*/`，但是还是不行，是我的正则表达式写错了吗

**Comment by LinWanCen** [comment]
# Python 不应开启，实验用的显示非正常注释，开启 Python 即可，正常情况是显示文档注释的
