### ISSUE TITLE
最近每天都有好多次自动崩溃

### ISSUE THREAD

**Issue by SophieRoyal** [LinWanCen/show-comment#5]
![image](https://user-images.githubusercontent.com/37917658/177722794-d6fc75e0-9bc1-4949-89c1-5e76d155954d.png)
![image](https://user-images.githubusercontent.com/37917658/177722854-3b52aa6f-4ab9-476b-b356-56c2ba59b648.png)

**Comment by LinWanCen** [comment]
1.19在 Override放在非方法的位置时会导致整个界面崩溃，请升级1.20
