### ISSUE TITLE
RustRover 文件旁边显示的内容多 !

### ISSUE THREAD

**Issue by bcdax110** [LinWanCen/show-comment#55]
Rust中的写在文件开头（包级别）的注释有两种写法：
- 行注释： `//!` 
- 块注释： `/*! ... */`
插件目前会把Rust语法中固定的`!`也当作注释的内容

比如文件exmaple.rs的内容是：
```rust
//! 示例包注释
```
在Project视图中显示的是`example.rs ! 示例包注释`，而正确的显示方式应该是`example.rs 示例包注释`

**Comment by LinWanCen** [comment]
哈哈，我看看这周抽时间改下
原来被我不小心点了不关注此项目所以一直没看到，自己的项目居然不关注没收到邮件🤣
