### ISSUE TITLE
希望能够支持配置开启或关闭行尾注释显示

### ISSUE THREAD

**Issue by IT-xiaoXiong** [LinWanCen/show-comment#6]
希望能够支持在idea中配置是否开启行尾注释，有时候注释太多，感觉idea写代码的时候有些凌乱，希望能支持这个配置，编写代码时能够更加简洁一些，代码阅读时打开方便查阅

**Comment by LinWanCen** [comment]
在设置tools找到插件的设置，第二个勾就是这个开关

**Comment by IT-xiaoXiong** [comment]
已成功接收到您的邮件，我会在短时间内回复您！
