### ISSUE TITLE
能否预加载注释呢

### ISSUE THREAD

**Issue by GitHub-jxy** [LinWanCen/show-comment#65]
作者你好，该插件非常有用，对我了解新项目有很大的帮助，但是我有一些小的想法，能否在项目启动的时候，自动的，快速的（重点），所有的文件，将注释加入显示在旁边呢

**Comment by LinWanCen** [comment]
你是指左侧的文件树注释？可以关闭文件树缓存异步加载，直接渲染就很快了，第二个勾选项

**Comment by LinWanCen** [comment]
我一直在犹豫要不要默认关闭文件树缓存，最新版默认关闭了。
