### ISSUE TITLE
Doesn't work for the SQL in a MyBatis mapper XML file

### ISSUE THREAD

**Issue by HubKing** [LinWanCen/show-comment#68]
It works for the SQL in the Query Console, but it does not work for the SQL in a MyBatis mapper XML file. The XML file contains SQL queries, and IntelliJ already recognises it and hightlights the syntax. So, I think this plugin can probably also work with some configuration change.

![image](https://github.com/user-attachments/assets/f8f5941c-b7a5-47ed-a617-fbe8576c9b1f)

**Comment by LinWanCen** [comment]
You can click column or table, Ctrl + Q see doc, Screenshot to me.
If you use IDEA Community, can use ext-doc, I have a demo.

**Comment by HubKing** [comment]
> You can click column or table, Ctrl + Q see doc, Screenshot to me. If you use IDEA Community, can use ext-doc, I have a demo.

As you see the screen capture below, within the same project, for the same SQL query, the query console shows the comment ("Comment1") after the query, but the SQL in the MyBatis does not show the comment, even though IntelliJ has parsed the SQL and can show the comment if I place the mouse pointer on the table name.

Yeah, I can use Ctrl + Q or place the mouse on the table to see the comment, but the reason I installed this plugin was to see the comments without doing those.

![image](https://github.com/user-attachments/assets/08e3eeed-6ccc-4d1e-93fe-760f16371757)

**Comment by LinWanCen** [comment]
It is good, I support it. 
[show-comment-2.17.0.2024.12.23_19.49.zip](https://github.com/user-attachments/files/18229058/show-comment-2.17.0.2024.12.23_19.49.zip)
