### ISSUE TITLE
怎样才能按包名过滤呢？

### ISSUE THREAD

**Issue by seyrenus** [LinWanCen/show-comment#7]
想把java包下面的所有类都exclude，但是试了正则  `^java.*` 发现没作用。

**Comment by LinWanCen** [comment]
默认就过滤了，在第二个里默认了^java\.的，你可以截图设置界面发这里，还有建议勾选skip English。

**Comment by LinWanCen** [comment]
构造方法可能不属于PsiMember所以没过滤到，我晚上看看

**Comment by LinWanCen** [comment]
1.17的时候就有问题了，方法的类名用错toString()，变成Psi:classSimpleName，已修复，待插件市场审核通过后更新版本1.20.1。
PS:最近在做兼容所有IDE和多语言的重构，搁置回来修bug🤣
