### ISSUE TITLE
右键菜单: // Add Line Comment 能否关闭?

### ISSUE THREAD

**Issue by song-yan-ru-mo** [LinWanCen/show-comment#8]
如题, 从内容上看是新建一个配置文件替换默认注释?  
这东西并不是必须, 即使需要, 它也应该进新建菜单的二级选项.  放在第一级第一个违反使用习惯.

我没有找到关于它的设置,  我需要关闭这个菜单选项 QAQ

![image](https://user-images.githubusercontent.com/40515646/183445279-3d104d42-dce8-4a00-ac57-73457f9fb82f.png)

**Comment by LinWanCen** [comment]
官方文档没有隐藏相关的资料，研究了下自带菜单知道怎么隐藏了，暂时先改到最后一项，待插件市场审核通过后更新1.22即可。

**Comment by song-yan-ru-mo** [comment]
感谢

我原来也想搞个插件玩的, 但是官方文档属实离谱 劝退了
