### ISSUE TITLE
怎么能过滤掉HTML文件？

### ISSUE THREAD

**Issue by lettgers** [LinWanCen/show-comment#9]

**Comment by LinWanCen** [comment]
是 HTML 代码上显示了注释？还是说文件树注释，目前目录注释的确会应用到所有目录和文件。

**Comment by lettgers** [comment]
![image](https://user-images.githubusercontent.com/30726330/185603221-cde89d7d-e1e4-44a6-8c7c-ef9ec60631a3.png)

**Comment by LinWanCen** [comment]
可否提供完整的堆栈文本，图上没看到插件所在的包io.github.linwancen

**Comment by LinWanCen** [comment]
看了下对应这个插件的源码顶端是在折叠中间包时显示上级包注释的功能处报错的。

https://github.com/LinWanCen/show-comment/blob/7fa464855a88d477f1dcee8cdb0d55abf82458a7/src/main/java/io/github/linwancen/plugin/show/Tree.java#L138

```
    @Nullable
    private static PsiDocComment dirDoc(PsiDirectory child) {
        while (true) {
            PsiDocComment docComment = OwnerToPsiDocUtils.dirDoc(child);
            if (docComment != null) {
                return docComment;
            }
            PsiDirectory parent = child.getParent();
            if (parent == null) {
                return null;
            }
            if (parent.getChildren().length != 1) {
                return null;
            }
            child = parent;
        }
    }
```

对应 IDEA 的代码顶端这里只是打日志没有抛异常，所以我也不好直接 try 来解决。

https://github.com/JetBrains/intellij-community/blob/9a9db7738edd926eb93903b3945d8247985338f4/platform/core-impl/src/com/intellij/psi/impl/file/impl/FileManagerImpl.java#L633
```
    if (tempProviders.containsKey(file)) {
      LOG.error(new StackOverflowPreventedException("isValid leads to endless recursion in " + viewProvider.getClass() + ": " + new ArrayList<>(viewProvider.getLanguages())));
    }
```

在提示这个问题后你的 IDEA 是否会出现 UI 崩溃？

具体为何触发原因暂时看不出来。

我可以提供一个开关用于关闭这个功能。

**Comment by lettgers** [comment]
好的感谢

**Comment by LinWanCen** [comment]
待插件市场 1.23 版本审核通过后更新版本，在设置界面去掉 compact 选项的勾即可。

**Comment by LinWanCen** [comment]
插件市场已通过
